# -*- coding: utf-8 -*-
"""4101E005_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkE0hGuwV5VPi28bhIhDrLcsB9tjOsQL
"""

# space without ","
x, y, z = [int(x) for x in input("Enter three value: ").split()] 
print("First Number is: ", x) 
print("Second Number is: ", y) 
print("Third Number is: ", z) 
print()

# "," without space
x, y, z = [int(x) for x in input("Enter three value: ").split(",")] 
print("First Number is: ", x) 
print("Second Number is: ", y) 
print("Third Number is: ", z) 
print()

a, b = input("Enter a two value: ").split() 
print("First number is {} and second number is {}".format(a, b)) 
print()